name: pypi_publish

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  wheels:
    name: Wheels & SDist
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build SDist and wheel
        run: uv build

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist/*

      - name: Check metadata
        run: uvx twine check dist/*

      - name: Install from wheel
        run: uv pip install --system "$(find dist -name 'duckboat-*-py3-none-any.whl' -type f -print -quit)"

      - name: Install test deps
        run: uv pip install --system pytest pytest-cov

      - name: Test wheel
        run: pytest

      - name: Install from sdist
        run: |
          uv pip uninstall --system duckboat
          cp dist/duckboat-*.tar.gz duckboat.tar.gz
          uv pip install --system duckboat.tar.gz

      - name: Test sdist
        run: pytest

  to_pypi:
    needs: [wheels]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
